### ISSUE TITLE
Clarify PubChem ID

### ISSUE THREAD

**Issue by egonw** [stuchalk/OSDB#22]
I assume PubChem ID refers to the CID, but since so many database even mix SIDs with CIDs, may I request this label in the Substance View to be relabeled to "PubChem CID" to remove ambiguity?

(PS. also consider submitting the substances to PubChem with OSDB as supplier...)

**Comment by stuchalk** [comment]
I will certainly consider submitting the substances (and potentially spectra) to PubChem...
