### ISSUE TITLE
Collections 4-8 are spam

### ISSUE THREAD

**Issue by egonw** [stuchalk/OSDB#23]
See http://osdb.info/collections: they have labels like flgceq and websites to increase Page Ranks for those pages.

**Comment by stuchalk** [comment]
Thanks for reporting this.  I have deleted them from the database.  I have also disabled access to http://osdb.info/collections/add for anyone not logged in.  FYI, while looking into this I see extra users that did not provide correct contact info so I will add that as an issue to fix.
