### ISSUE TITLE
plz consider adding SPLASHes for mz spectra

### ISSUE THREAD

**Issue by egonw** [stuchalk/OSDB#26]
See https://github.com/berlinguyinca/spectra-hash

**Comment by stuchalk** [comment]
I'm happy to implement this.  I should have something up by the end of this week.

**Comment by egonw** [comment]
Great!

**Comment by berlinguyinca** [comment]
thanks, we will update the website and add a link to your resources as soon as we hear that it's done, if this is ok with you?

**Comment by stuchalk** [comment]
Absolutely that's fine!  Thanks.

**Comment by egonw** [comment]
Stuart, I'm requested the SPLASH to be listed in MIRIAM [0]. Please do let me know if the API will support linking to a spectrum using the SPLASH, like the MoNA example in report [0]. Then we can request listing your DB as "resource" too!

0.https://sourceforge.net/p/identifiers-org/new-collection/30/

**Comment by stuchalk** [comment]
Egon, I am happy to put that in code.  However, I am still looking for how to build splash JSON for NMR, and IR so I can get splashes for those spectra.  Having searched the splashes repo for NMR and IR related words, it does not seem as though they are implemented yet.  I would rather add splashes all at once, however if its going to take a while to get NMR and IR working please let me know as I am writing a paper on the website and hoping to get it submitted by Friday next week.

**Comment by egonw** [comment]
NMR will take longer (a lot beyond next week Friday); this specification is yet to start. It would help us a lot of you could roll it out for MS.

**Comment by stuchalk** [comment]
OK, no problem. Looking back at the ticket title I had not noticed the request was for mz spectra until about 15 minutes ago...  So, I thought you had them all done...

**Comment by berlinguyinca** [comment]
dear all,

thanks and yes the NMR splash will need a little bit longer, but we are
open for any suggestions!

g.

On Thu, Feb 4, 2016 at 10:29 AM, Stuart Chalk <notifications@github.com>
wrote:

> OK, no problem. Looking back at the ticket title I had not noticed the
> request was for mz spectra until about 15 minutes ago... So, I thought you
> had them all done...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stuchalk/OSDB/issues/26#issuecomment-179984013>.
>



-- 
------------------------------------------------------------
Lead Developer - Fiehnlab, UC Davis

gert wohlgemuth

work:
http://fiehnlab.ucdavis.edu/staff/wohlgemuth

phone:
530 665 9477

coding blog:
http://codingandmore.blogspot.com

linkedin:
http://www.linkedin.com/profile/view?id=28611299&trk=tab_pro

**Comment by stuchalk** [comment]
Well, for NMR you would have "chemical shift" for the label of the x-axis data and "intensity" for y-axis.
For IR you would have "wavenumber" for the x-axis and "transittance" for the y-axis.  Maybe you also allow "percent transmittance" for the y-axis.

**Comment by stuchalk** [comment]
OK, splashes are now supported for MS data!

**Comment by egonw** [comment]
Super, huge thanx!
