### ISSUE TITLE
statistics page

### ISSUE THREAD

**Issue by egonw** [stuchalk/OSDB#29]
Maybe it is an idea to have a basic statistics page with some overall numbers, particularly highlighting the growth and momentum of the database?

**Comment by stuchalk** [comment]
This is great idea.  The only issue at this point is the lack of growth/momentum.  I am the only one to add spectra at this point ( :( ) and I need to add a lot more over the next couple of weeks as I am hoping that a paper I have submitted to J. Chem. Inf. gets accepted.
